version: '3'
services:
  whisper:
    volumes:
      - ./:/app
    build: .
    ports:
      - 8080:8080
    deploy:
      resources:
        reservations:
          devices:
           - driver: nvidia
             capabilities: [utility, compute, video]